FROM ubuntu:precise

MAINTAINER Paul Czarkowski

VOLUME /pkg

RUN apt-get -y update && apt-get install -y wget iputils-ping expect curl automake vim build-essential ruby-dev rubygems && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN gem install fpm --no-ri --no-rdoc

ENV DISTRO precise

ADD build.sh /tmp/build.sh

RUN chmod +x /tmp/build.sh

CMD /tmp/build.sh


WORKDIR /pkg

